#!/usr/bin/env bash
echo "
IMAGE DEPLOY INFO
-----------------
label               ${VWC_LABEL}
description         ${VWC_DESCRIPTION}

realm               ${VWC_REALM_RUNTIME}
ecosystem           ${VWC_ECOSYSTEM_RUNTIME}

image-type          ${VWC_IMAGE}
instance-name       ${VWC_FLAVOR}
image-tag           ${VWC_TAG}

base-image          ${VWC_BASE}
image-build         ${VWC_BUILD}

stack-names         ${VWC_CD_GLOBAL_STACKNAMES}
boot-stacks         ${VWC_CD_GLOBAL_BOOTSTACKS}
run-stacks          ${VWC_CD_GLOBAL_RUNSTACKS}
volume-list         ${VWC_CD_GLOBAL_VOLUME_LIST}
"
