#!/usr/bin/env bash
echo "
IMAGE DEPLOY INFO
-----------------
label               ${VCWC_LABEL}
description         ${VCWC_DESCRIPTION}

realm               ${VCWC_REALM_RUNTIME}
ecosystem           ${VCWC_ECOSYSTEM_RUNTIME}

image-type          ${VCWC_IMAGE}
instance-name       ${VCWC_FLAVOR}
image-tag           ${VCWC_TAG}

base-image          ${VCWC_BASE}
image-build         ${VCWC_BUILD}

stack-names         ${VCWC_CD_GLOBAL_STACKNAMES}
boot-stacks         ${VCWC_CD_GLOBAL_BOOTSTACKS}
run-stacks          ${VCWC_CD_GLOBAL_RUNSTACKS}
volume-list         ${VCWC_CD_GLOBAL_VOLUME_LIST}
"
