#!/usr/bin/env bash
echo "
IMAGE REPO INFO
---------------
label               ${VCWC_LABEL}
description         ${VCWC_DESCRIPTION}
realm               ${VCWC_REALM_RUNTIME}
ecosystem           ${VCWC_ECOSYSTEM_RUNTIME}
image-type          ${VCWC_IMAGE}
instance-name       ${VCWC_FLAVOR}
image-tag           ${VCWC_TAG}
base-image          ${VCWC_BASE}
image-build         ${VCWC_BUILD}
"
